sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: 奉伟的博客
name: 一个95后，不抽烟喝酒，没事天天发愁的程序员小哥
description: Always believe that something wonderful is about to happen.

github: https://github.com/LiuFwei
rss: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
